# Services
# APP_NAME=unsplashapp
# SERVICE_NAME=unsplashapp
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  labels:
    app: $APP_NAME
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: $APP_NAME
EOF
# Deployments
# Gateways (Ingress)
# GATEWAY_NAME=unsplashapp
# Nginx Config:                                    #
# proxy_set_header Host www.fewbox.com; // $host   #
# proxy_set_header X-Forwarded-For $remote_addr;   #
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: $GATEWAY_NAME
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
EOF
# ServiceEntries (Egress)